### ISSUE TITLE
API broken for you as well?

### ISSUE THREAD

**Issue by swrobel** [mhelmetag/surflinef#1]
Seems like they might've finally shut off the legacy API. [My app](https://github.com/swrobel/meta-surf-forecast) doesn't seem to be able to fetch from it anymore, just getting 503 errors...

**Comment by mhelmetag** [comment]
Huh! Sorry for the late reply. I guess I don't watch my repos closely enough 😅

I haven't noticed any difference. Maybe it was down when you were getting 503s?

I use this library for a CLI tool so I probably don't see much nuance in responses (since I use it during the day and infrequently).

On that note, have you looked at their new API at all? Only gives 6 days (one less than legacy) but they have a new locations API which is kinda nice (I've been using another project of mine surfliner.maxworld.tech to get location IDs; basically a cache of old location IDs and names in a JSON API).

**Comment by swrobel** [comment]
Seems like it was down for about a week or so, but it's back. I haven't used the new API, but 6 days isn't very encouraging...

**Comment by mhelmetag** [comment]
Interesting! I wondering if that's foreshadowing (of them deprecating the legacy API).

I do have a hunch that the new API is actually just a wrapper around the old API (if so, I don't think it's going away any time soon) but... I could be wrong.

**Comment by swrobel** [comment]
Wow, just found your wrapper around the regions API, which is awesome! Have you figured out how to get all spot ids in a subregion? I've gotten as far as http://surfliner.maxworld.tech/api/areas/4716/regions/52737/subregions/2132

**Comment by mhelmetag** [comment]
Oof... spot IDs? I thought spots were a new API thing?

That is basically just a cache of the old area, region and subregion trees for the old API.

Maybe spots are in the subregion endpoint using one of those `allSpots` flags?

I basically just use this for subregion forecasts.

**Comment by mhelmetag** [comment]
There's the new taxonomy API which has all the spots for the new API. Haven't played around with it much though.
